### PR TITLE
Adds Field pubmed to publications

### PR DESCRIPTION
**Pull request by karliwalti**
Addresses feature request in #36

### CODE REVIEW

**Review by mschwemer — DISMISSED** [review]
I don't think, that the label "Karlwalti..." is meant for production ;-) 

Can you provide a better one?

Thx

**Comment by mschwemer** [comment]
Should we add the pmid to the link-block partials, like `DOI` and `ISBN`? Then all fields of a publication would be shown by default. 

(BTW: `ISBN` is also not linked)

**Comment by karliwalti** [comment]
I presume you mean here?
https://github.com/in2code-de/publications/blob/e6f5c886170804815d743f6f3a82cba6f3077d1a/Resources/Private/Partials/List/Citestyle/LinkBlock.html#L15

In the inline version I did already prepare it as link: https://github.com/in2code-de/publications/blob/e6f5c886170804815d743f6f3a82cba6f3077d1a/Resources/Private/Partials/List/Citestyle/LinkBlock-Inline.html#L21

**Comment by mschwemer** [comment]
Yes, that's exactly what I meant :-) 

I did not see this, because the topics of both PRs diverge. 

If you don't mind, I would add that also to the "normal" link block and the merge your PR.

**Pull request merged**
