### PR TITLE
10

### PR DESCRIPTION
**Pull request by snaegle**
With these changes, publications works with TYPO3 10.

### CODE REVIEW

**Comment by einpraegsam** [comment]
Thx for your work. So you would support TYPO3 8-10? And you have tested your changes in TYPO3 8LTS?

**Comment by snaegle** [comment]
I testet it with TYPO3 10.4,9.5,8.7 and PHP 7.4,7.1 and it worked

**Comment by einpraegsam** [comment]
Hmm, I did not test it but if I look into your changes where you remove `@validate $importer \In2code\Publications\Validation\Validator\ClassValidator and UploadValidator` I think that this validator is stopped working in TYPO3 8 - isn't it?
I would drop TYPO3 8 support.

**Comment by snaegle** [comment]
Support for 8 is now dropped. Thx for your comment.

**Pull request merged**
